inherit_gem:
  ruboconfig: rubocop.yml

AllCops:
  DisplayCopNames: true
  Exclude:
    - vendor/**/*
    - .*/**
    - spec/fixtures/**/*

StringLiterals:
  Enabled: false

MethodLength:
  CountComments: false
  Max: 15

AbcSize:
  Max: 18

LineLength:
  Max: 80

# Allow class and message or instance raises
Style/RaiseArgs:
  Enabled: false

Lint/RescueWithoutErrorClass:
  Enabled: false
