# For all options see https://github.com/bbatsov/rubocop/tree/master/config

AllCops:
  Include:
    - Rakefile
    - statesman.gemfile
  Exclude:
    - vendor/**
    - .*/**

StringLiterals:
  Enabled: false

Documentation:
  Enabled: false

SignalException:
  Enabled: false

# Avoid methods longer than 30 lines of code
MethodLength:
  CountComments: false  # count full line comments?
  Max: 15

AbcSize:
  Max: 25

# Don't require utf-8 encoding comment
Encoding:
  Enabled: false

LineLength:
  Max: 80

GuardClause:
  Enabled: false

SingleSpaceBeforeFirstArg:
  Enabled: false
