# For all options see https://github.com/bbatsov/rubocop/tree/master/config

AllCops:
  Include:
    - Rakefile
    - statesman.gemfile
    - lib/tasks/*.rake
  Exclude:
    - vendor/**/*
    - .*/**
    - spec/fixtures/**/*

StringLiterals:
  Enabled: false

Documentation:
  Enabled: false

SignalException:
  EnforcedStyle: only_raise

# Avoid methods longer than 15 lines of code
MethodLength:
  CountComments: false
  Max: 15

AbcSize:
  Max: 25

# Don't require utf-8 encoding comment
Encoding:
  Enabled: false

LineLength:
  Max: 85

GuardClause:
  Enabled: false

SingleSpaceBeforeFirstArg:
  Enabled: false

DotPosition:
  EnforcedStyle: trailing

# Allow class and message or instance raises
Style/RaiseArgs:
  Enabled: false
