inherit_from: .rubocop_todo.yml

inherit_gem:
  gc_ruboconfig: rubocop.yml

AllCops:
  TargetRubyVersion: 3.0
  NewCops: enable

Metrics/AbcSize:
  Max: 60

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/PerceivedComplexity:
  Max: 11

Gemspec/DevelopmentDependencies:
  Enabled: false
