version: '3.8'

services:
  ruby:
    image: mcr.microsoft.com/devcontainers/ruby:1-3.4-bullseye
    volumes:
      - ..:/workspace:cached
      - gem-cache:/usr/local/rvm/gems/default
    command: sleep infinity
    depends_on:
      - postgres
      - mysql

  postgres:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: statesman_dev
    volumes:
      - postgres-data:/var/lib/postgresql/data
    expose:
      - "5432"

  mysql:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: statesman_dev
    volumes:
      - mysql-data:/var/lib/mysql
    expose:
      - "3306"

volumes:
  postgres-data:
  mysql-data:
  gem-cache: